wip

diff --git a/compose/aero b/compose/aero
--- a/compose/aero
+++ b/compose/aero
@@ -371,6 +371,10 @@ if [ $# -gt 0 ]; then
     elif [ "$1" == "new" ]; then
         update_check
         shift 1
+        if [ $# -eq 0 ]; then
+            echo -e "${YELLOW}Not enough arguments (missing: \"store name\").${NC}" >&2
+            exit 1
+        fi
         if [ -d "$PWD/$1" ]; then
             echo -e "${YELLOW}A directory with this name already exists.${NC}"
             exit 1
@@ -424,7 +428,7 @@ if [ $# -gt 0 ]; then
     elif [ "$1" == "self-update" ]; then
         if curl -s https://raw.githubusercontent.com/timrspratt/aero-docker/1.x/install.sh | bash -s 1;
         then
-            echo -e "${GREEN}Updated.${NC}" >&2
+            echo -e "${GREEN}Updated!${NC}" >&2
         else
             echo -e "${YELLOW}There was a problem updating.${NC}" >&2
             exit 1
